/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PainPointsRouteImport } from './routes/pain-points'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated/access'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConfigurationRouteImport } from './routes/_authenticated/configuration'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedFarmHistoryRouteImport } from './routes/_authenticated/farm-history'
import { Route as AuthenticatedFpoRouteImport } from './routes/_authenticated/fpo'
import { Route as AuthenticatedFpoOpportunityRouteImport } from './routes/_authenticated/fpo-opportunity'
import { Route as AuthenticatedInputsRouteImport } from './routes/_authenticated/inputs'
import { Route as AuthenticatedInsurerRouteImport } from './routes/_authenticated/insurer'
import { Route as AuthenticatedInsurerClaimsRouteImport } from './routes/_authenticated/insurer-claims'
import { Route as AuthenticatedInsurerPoliciesRouteImport } from './routes/_authenticated/insurer-policies'
import { Route as AuthenticatedInsurerRiskRouteImport } from './routes/_authenticated/insurer-risk'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPracticesRouteImport } from './routes/_authenticated/practices'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedRolloutRouteImport } from './routes/_authenticated/rollout'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedSoilCareRouteImport } from './routes/_authenticated/soil-care'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PainPointsRoute = PainPointsRouteImport.update({
  id: '/pain-points',
  path: '/pain-points',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigurationRoute =
  AuthenticatedConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmHistoryRoute =
  AuthenticatedFarmHistoryRouteImport.update({
    id: '/farm-history',
    path: '/farm-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFpoRoute = AuthenticatedFpoRouteImport.update({
  id: '/fpo',
  path: '/fpo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFpoOpportunityRoute =
  AuthenticatedFpoOpportunityRouteImport.update({
    id: '/fpo-opportunity',
    path: '/fpo-opportunity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInputsRoute = AuthenticatedInputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsurerRoute = AuthenticatedInsurerRouteImport.update({
  id: '/insurer',
  path: '/insurer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsurerClaimsRoute =
  AuthenticatedInsurerClaimsRouteImport.update({
    id: '/insurer-claims',
    path: '/insurer-claims',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsurerPoliciesRoute =
  AuthenticatedInsurerPoliciesRouteImport.update({
    id: '/insurer-policies',
    path: '/insurer-policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsurerRiskRoute =
  AuthenticatedInsurerRiskRouteImport.update({
    id: '/insurer-risk',
    path: '/insurer-risk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticesRoute = AuthenticatedPracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolloutRoute = AuthenticatedRolloutRouteImport.update({
  id: '/rollout',
  path: '/rollout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoilCareRoute = AuthenticatedSoilCareRouteImport.update({
  id: '/soil-care',
  path: '/soil-care',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/pain-points': typeof PainPointsRoute
  '/platform': typeof PlatformRoute
  '/roles': typeof RolesRoute
  '/team': typeof TeamRoute
  '/access': typeof AuthenticatedAccessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/farm-history': typeof AuthenticatedFarmHistoryRoute
  '/fpo': typeof AuthenticatedFpoRoute
  '/fpo-opportunity': typeof AuthenticatedFpoOpportunityRoute
  '/inputs': typeof AuthenticatedInputsRoute
  '/insurer': typeof AuthenticatedInsurerRoute
  '/insurer-claims': typeof AuthenticatedInsurerClaimsRoute
  '/insurer-policies': typeof AuthenticatedInsurerPoliciesRoute
  '/insurer-risk': typeof AuthenticatedInsurerRiskRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/market': typeof AuthenticatedMarketRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practices': typeof AuthenticatedPracticesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/rollout': typeof AuthenticatedRolloutRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/soil-care': typeof AuthenticatedSoilCareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/pain-points': typeof PainPointsRoute
  '/platform': typeof PlatformRoute
  '/roles': typeof RolesRoute
  '/team': typeof TeamRoute
  '/access': typeof AuthenticatedAccessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuration': typeof AuthenticatedConfigurationRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/farm-history': typeof AuthenticatedFarmHistoryRoute
  '/fpo': typeof AuthenticatedFpoRoute
  '/fpo-opportunity': typeof AuthenticatedFpoOpportunityRoute
  '/inputs': typeof AuthenticatedInputsRoute
  '/insurer': typeof AuthenticatedInsurerRoute
  '/insurer-claims': typeof AuthenticatedInsurerClaimsRoute
  '/insurer-policies': typeof AuthenticatedInsurerPoliciesRoute
  '/insurer-risk': typeof AuthenticatedInsurerRiskRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/market': typeof AuthenticatedMarketRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practices': typeof AuthenticatedPracticesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/rollout': typeof AuthenticatedRolloutRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/soil-care': typeof AuthenticatedSoilCareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/pain-points': typeof PainPointsRoute
  '/platform': typeof PlatformRoute
  '/roles': typeof RolesRoute
  '/team': typeof TeamRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/configuration': typeof AuthenticatedConfigurationRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/farm-history': typeof AuthenticatedFarmHistoryRoute
  '/_authenticated/fpo': typeof AuthenticatedFpoRoute
  '/_authenticated/fpo-opportunity': typeof AuthenticatedFpoOpportunityRoute
  '/_authenticated/inputs': typeof AuthenticatedInputsRoute
  '/_authenticated/insurer': typeof AuthenticatedInsurerRoute
  '/_authenticated/insurer-claims': typeof AuthenticatedInsurerClaimsRoute
  '/_authenticated/insurer-policies': typeof AuthenticatedInsurerPoliciesRoute
  '/_authenticated/insurer-risk': typeof AuthenticatedInsurerRiskRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practices': typeof AuthenticatedPracticesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/rollout': typeof AuthenticatedRolloutRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/soil-care': typeof AuthenticatedSoilCareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/pain-points'
    | '/platform'
    | '/roles'
    | '/team'
    | '/access'
    | '/admin'
    | '/configuration'
    | '/consent'
    | '/dashboard'
    | '/discovery'
    | '/farm'
    | '/farm-history'
    | '/fpo'
    | '/fpo-opportunity'
    | '/inputs'
    | '/insurer'
    | '/insurer-claims'
    | '/insurer-policies'
    | '/insurer-risk'
    | '/intelligence'
    | '/market'
    | '/onboarding'
    | '/practices'
    | '/profile'
    | '/review'
    | '/rollout'
    | '/schemes'
    | '/soil-care'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/pain-points'
    | '/platform'
    | '/roles'
    | '/team'
    | '/access'
    | '/admin'
    | '/configuration'
    | '/consent'
    | '/dashboard'
    | '/discovery'
    | '/farm'
    | '/farm-history'
    | '/fpo'
    | '/fpo-opportunity'
    | '/inputs'
    | '/insurer'
    | '/insurer-claims'
    | '/insurer-policies'
    | '/insurer-risk'
    | '/intelligence'
    | '/market'
    | '/onboarding'
    | '/practices'
    | '/profile'
    | '/review'
    | '/rollout'
    | '/schemes'
    | '/soil-care'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/architecture'
    | '/auth'
    | '/pain-points'
    | '/platform'
    | '/roles'
    | '/team'
    | '/_authenticated/access'
    | '/_authenticated/admin'
    | '/_authenticated/configuration'
    | '/_authenticated/consent'
    | '/_authenticated/dashboard'
    | '/_authenticated/discovery'
    | '/_authenticated/farm'
    | '/_authenticated/farm-history'
    | '/_authenticated/fpo'
    | '/_authenticated/fpo-opportunity'
    | '/_authenticated/inputs'
    | '/_authenticated/insurer'
    | '/_authenticated/insurer-claims'
    | '/_authenticated/insurer-policies'
    | '/_authenticated/insurer-risk'
    | '/_authenticated/intelligence'
    | '/_authenticated/market'
    | '/_authenticated/onboarding'
    | '/_authenticated/practices'
    | '/_authenticated/profile'
    | '/_authenticated/review'
    | '/_authenticated/rollout'
    | '/_authenticated/schemes'
    | '/_authenticated/soil-care'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  PainPointsRoute: typeof PainPointsRoute
  PlatformRoute: typeof PlatformRoute
  RolesRoute: typeof RolesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pain-points': {
      id: '/pain-points'
      path: '/pain-points'
      fullPath: '/pain-points'
      preLoaderRoute: typeof PainPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuration': {
      id: '/_authenticated/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthenticatedConfigurationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm-history': {
      id: '/_authenticated/farm-history'
      path: '/farm-history'
      fullPath: '/farm-history'
      preLoaderRoute: typeof AuthenticatedFarmHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fpo': {
      id: '/_authenticated/fpo'
      path: '/fpo'
      fullPath: '/fpo'
      preLoaderRoute: typeof AuthenticatedFpoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fpo-opportunity': {
      id: '/_authenticated/fpo-opportunity'
      path: '/fpo-opportunity'
      fullPath: '/fpo-opportunity'
      preLoaderRoute: typeof AuthenticatedFpoOpportunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inputs': {
      id: '/_authenticated/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof AuthenticatedInputsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurer': {
      id: '/_authenticated/insurer'
      path: '/insurer'
      fullPath: '/insurer'
      preLoaderRoute: typeof AuthenticatedInsurerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurer-claims': {
      id: '/_authenticated/insurer-claims'
      path: '/insurer-claims'
      fullPath: '/insurer-claims'
      preLoaderRoute: typeof AuthenticatedInsurerClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurer-policies': {
      id: '/_authenticated/insurer-policies'
      path: '/insurer-policies'
      fullPath: '/insurer-policies'
      preLoaderRoute: typeof AuthenticatedInsurerPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurer-risk': {
      id: '/_authenticated/insurer-risk'
      path: '/insurer-risk'
      fullPath: '/insurer-risk'
      preLoaderRoute: typeof AuthenticatedInsurerRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practices': {
      id: '/_authenticated/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof AuthenticatedPracticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rollout': {
      id: '/_authenticated/rollout'
      path: '/rollout'
      fullPath: '/rollout'
      preLoaderRoute: typeof AuthenticatedRolloutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soil-care': {
      id: '/_authenticated/soil-care'
      path: '/soil-care'
      fullPath: '/soil-care'
      preLoaderRoute: typeof AuthenticatedSoilCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConfigurationRoute: typeof AuthenticatedConfigurationRoute
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedFarmHistoryRoute: typeof AuthenticatedFarmHistoryRoute
  AuthenticatedFpoRoute: typeof AuthenticatedFpoRoute
  AuthenticatedFpoOpportunityRoute: typeof AuthenticatedFpoOpportunityRoute
  AuthenticatedInputsRoute: typeof AuthenticatedInputsRoute
  AuthenticatedInsurerRoute: typeof AuthenticatedInsurerRoute
  AuthenticatedInsurerClaimsRoute: typeof AuthenticatedInsurerClaimsRoute
  AuthenticatedInsurerPoliciesRoute: typeof AuthenticatedInsurerPoliciesRoute
  AuthenticatedInsurerRiskRoute: typeof AuthenticatedInsurerRiskRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticesRoute: typeof AuthenticatedPracticesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedRolloutRoute: typeof AuthenticatedRolloutRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedSoilCareRoute: typeof AuthenticatedSoilCareRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConfigurationRoute: AuthenticatedConfigurationRoute,
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedFarmHistoryRoute: AuthenticatedFarmHistoryRoute,
  AuthenticatedFpoRoute: AuthenticatedFpoRoute,
  AuthenticatedFpoOpportunityRoute: AuthenticatedFpoOpportunityRoute,
  AuthenticatedInputsRoute: AuthenticatedInputsRoute,
  AuthenticatedInsurerRoute: AuthenticatedInsurerRoute,
  AuthenticatedInsurerClaimsRoute: AuthenticatedInsurerClaimsRoute,
  AuthenticatedInsurerPoliciesRoute: AuthenticatedInsurerPoliciesRoute,
  AuthenticatedInsurerRiskRoute: AuthenticatedInsurerRiskRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticesRoute: AuthenticatedPracticesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedRolloutRoute: AuthenticatedRolloutRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedSoilCareRoute: AuthenticatedSoilCareRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  PainPointsRoute: PainPointsRoute,
  PlatformRoute: PlatformRoute,
  RolesRoute: RolesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
